### PR TITLE
update how UFS names restarts

### PR DESCRIPTION
**Pull request by DeniseWorthen**
* write all restarts as YYYYMMDD.HHMMSS.MOM.resX
* includes stoch restarts
* write final restart with timestamp
* change nems=>ufs

### CODE REVIEW

**Comment by jiandewang** [comment]
@DeniseWorthen let's work in the following orders:
(1) wait for unstructured kstokes PR being merged to main (just need one more approval, shall come early coming week)
(2) I created PR to pull it back to dev/emc (as this commit contains fixing for ci), asking Jong to give me high priority to combine it with other coming PR to merge to dev/emc
(3) you sync your branch
(4) you have UFS PR and we merge to MOM6 dev/emc 
(5) push back to MOM6 main (I will coordinate with GFDL on whether it goes ahead or after their PR, it's unlikely that your PR will cause conflict)

**Comment by DeniseWorthen** [comment]
@jiandewang That all sounds fine. Thanks.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@jiandewang We need approval before we start the UFS RT testing.

**Review by jiandewang — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@jiandewang We're ready for the MOM6 merge. Thanks.

**Comment by jiandewang** [comment]
> @jiandewang We're ready for the MOM6 merge. Thanks.

done

**Pull request merged**
