### PR TITLE
update to main 20240729 commit (gfdl-to-main-2024-05-31)

### PR DESCRIPTION
**Pull request by jiandewang**
MOM6 main repo. merged the "gfdl-to-main-2024-05-31" on 20240729 (see detail at https://github.com/mom-ocean/MOM6/pull/1631). Need to pull it into dev/emc correspondingly.
Note this PR will require a new BL because

- a new variable "h_ML" is being added in the restart file (see detail at https://github.com/mom-ocean/MOM6/commit/7305528fd99bc09bda648693cd7130e4627de25c)
- a  bug fixing on "incorrect PPM:H3 tracer advection stencil" (see detail at 3fac1c5a). Note we can retain original answer by setting USE_HUYNH_STENCIL_BUG=True.

we will also set DEFAULT_ANSWER_DATE=20231231 in 5x5 setting as currently it is using its default value which is too aggressive (suggested by GFDL)

note the switch FIX_USTAR_GUSTLESS_BUG=F to USTAR_GUSTLESS_BUG=T (they give same answer but  FIX_USTAR_GUSTLESS_BUG is going to be obsolated)

### CODE REVIEW

**Comment by jiandewang** [comment]
ready for review

**Comment by zach1221** [comment]
Hi, @DeniseWorthen . I think we may try to test PR 2381 next. Are you able to review here?

**Review by DeniseWorthen — COMMENTED** [review]
approve based on  RT testing.

**Comment by jiandewang** [comment]
@DeniseWorthen seems you forgot to click the approval botton

**Review by DeniseWorthen — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
PR [2381](https://github.com/ufs-community/ufs-weather-model/pull/2381) testing is complete, please continue with the merge process, thank you.

**Comment by jiandewang** [comment]
Is it the time for me to do MOM6 merging ?

**Comment by zach1221** [comment]
> Is it the time for me to do MOM6 merging ?

Yes, please!

**Comment by jiandewang** [comment]
merged

**Pull request merged**
