### PR TITLE
cap update: supporting traditional and ESMF-managed threading

### PR DESCRIPTION
**Pull request by junwang-noaa**
Code changes are made by Gerhard. The changes are to resolve an inconsistency between traditional and ESMF-managed threading under MOM6. Basically the original threading code tries to do some threading management locally in the cap, and through this essentially turns it off for the traditional approach. ESMF-managed does not suffer from it, because it manages threading on a lower level, and is unaffected by this code. But it does lead to the weird inconsistency that no matter what OMP_NUM_THREADS is set for traditional, MOM6 will always run single threaded. The local threading management code is removed in this PR.

Co-authored-by: Gerhard Theurich <gerhard.j.theurich@noaa.gov>

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@theurich @jiandewang FYI.

**Comment by jiandewang** [comment]
@junwang-noaa @theurich What I can see is that you removed those open-mp block in cap code, I will ask NCAR to do a pre-test to make sure the change will not break their system.
Your branch is based on 20220603 MOM6 main repo updating while there is another MOM6 main updating (20220729) which is in UFS commit queue. So I am going to make a branch based on 20220729 but adding your cap code change, in this way NCAR side can tell exactly what's being changed as dev/ncar is in parallel with 20220729 updating.

**Comment by junwang-noaa** [comment]
@jiandewang Thank you for coordinating the code commit!

**Comment by jiandewang** [comment]
@junwang-noaa we got greenlight from NCAR, so I am going to add your cap change in my pending MOM6 PR https://github.com/NOAA-EMC/MOM6/pull/99, and UFS PR https://github.com/ufs-community/ufs-weather-model/pull/1358

**Comment by jiandewang** [comment]
this is done through https://github.com/NOAA-EMC/MOM6/pull/99

**Pull request closed without merging**
