### PR TITLE
update to MOM6 main 20230504 updating

### PR DESCRIPTION
**Pull request by jiandewang**
MOM6 main repository is updated on 20230504, need to make corresponding updating in dev/emc. See detail at https://github.com/mom-ocean/MOM6/pull/1599 and https://github.com/mom-ocean/MOM6/pull/1594. Related dev/emc issue is #112. No answer change is expected in UFS.

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]
Approving based on pre-testing showing no-baseline change.

**Comment by FernandoAndrade-NOAA** [comment]
@JessicaMeixner-NOAA, Testing is complete on PR #[1736](https://github.com/ufs-community/ufs-weather-model/pull/1736), could you please merge this sub-pr, as it's been approved?

**Comment by jiandewang** [comment]
> @JessicaMeixner-NOAA, Testing is complete on PR #[1736](https://github.com/ufs-community/ufs-weather-model/pull/1736), could you please merge this sub-pr, as it's been approved?

@FernandoAndrade-NOAA I am going to merge MOM6 and do the git revert

**Comment by jiandewang** [comment]
MOM6 merged, ufs-weather-model submodule reverted

**Pull request merged**
