### PR TITLE
update to MOM6 main branch 20220317 commit

### PR DESCRIPTION
**Pull request by jiandewang**
need to update dev/emc MOM6, see detail at #86

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
That works but I've only tested it within the DA work we are doing. Is incremental update part of your testing @jiandewang ?

**Comment by jiandewang** [comment]
@guillaumevernieres thanks for your quick testing, I am not testing ODA in UFS

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang @guillaumevernieres do we need to add to or create a new regression tests in ufs-weather-model that runs with an incremental update in MOM6?  We could either do it for a C96 or a CDEPS set-up? I assume either would be sufficient?

**Comment by jiandewang** [comment]
that's something that either @guillaumevernieres or Phil can do. Actually the feature in this PR is exactly what Phil is looking for.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jiandewang** [comment]
this is combined and done with https://github.com/ufs-community/ufs-weather-model/pull/1136 in UFS

**Pull request merged**
