### PR TITLE
Update to GFDL 20200401 dev/master

### PR DESCRIPTION
**Pull request by jiandewang**
GFDL updated dev/master on 20200401, need to update EMC repository (issue #17 )
It has been tested in ufs-s2s-model successfully without answer change.
run log can be found on HERA at /scratch1/NCEPDEV/stmp2/Jiande.Wang/scrub/rtgen.3186/tmp/log

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jiandewang : can you explain what change you are making in this commit (https://github.com/jiandewang/MOM6/commit/b41878b26ec2086971b5ca244853e1af27b6182d)

**Comment by JessicaMeixner-NOAA** [comment]
I did a diff between the branch in this PR and GFDL's dev/master and the only difference was: 

```
diff -r MOM6gfdl/src/user/MOM_wave_interface.F90 MOM6jw/src/user/MOM_wave_interface.F90
1024a1025,1026
>   UStokes_sl = 0.0
>   LA=1.e8
1072,1075c1074
<     LA = sqrt(US%Z_to_m*US%s_to_T*ustar / UStokes_sl)
<   else
<     UStokes_sl = 0.0
<     LA=1.e8
---
>     if(UStokes_sl .ne. 0.0)LA = sqrt(US%Z_to_m*US%s_to_T*ustar / UStokes_sl)
```

which we added to run in debug mode.

**Comment by jiandewang** [comment]
Jessica: you are right, that piece of code was added by Denise in order to run in debug mode

**Comment by jiandewang** [comment]
Denise: this time GFDL dev/master merged NCAR-dev-master-candidate-2020-03-27 branch, as always, there is no detail explanation on what's new

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang There's some detail of what was committed in the GFDL PR here https://github.com/NOAA-GFDL/MOM6/pull/1081 

I think @DeniseWorthen was asking to know more details about how the conflict was resolved in the commit you made here: https://github.com/jiandewang/MOM6/commit/b41878b26ec2086971b5ca244853e1af27b6182d

**Comment by jiandewang** [comment]
conflict is at "mom_surface_forcing_nuopc.F90" on the use of "kg_m2_s_conversion"
<       fluxes%lrunoff(i,j) = IOB%lrunoff(i-i0,j-j0) * G%mask2dT(i,j)
---
>       fluxes%lrunoff(i,j) = kg_m2_s_conversion * IOB%lrunoff(i-i0,j-j0) * G%mask2dT(i,j)
452c452
<       fluxes%frunoff(i,j) = IOB%frunoff(i-i0,j-j0) * G%mask2dT(i,j)
---
>       fluxes%frunoff(i,j) = kg_m2_s_conversion * IOB%frunoff(i-i0,j-j0) * G%mask2dT(i,j)
468c468
<       fluxes%heat_content_frunoff(i,j) = IOB%frunoff_hflx(i-i0,j-j0) * G%mask2dT(i,j)
---
>       fluxes%heat_content_frunoff(i,j) = kg_m2_s_conversion * IOB%frunoff_hflx(i-i0,j-j0) * G%mask2dT(i,j)

**Comment by jiandewang** [comment]
there is no input change.
Denise: can you check the new code "MOM_wave_interface.F90" to make sure it contains the minor change you made in order to be able to run debug mode?

**Comment by DeniseWorthen** [comment]
I don't understand what you are saying is a conflict. If I look at GFDL's repo for master (010492e) when they merged in ncar's pr,  the thing that changed is the name of the fields. Those should be what we have already since ncar had merged our field name changes to dev/ncar back when we were working on this. 

When you merge in GFDL's master candidate, are you pushing the merge prior to fixing all the conflicts?

**Comment by jiandewang** [comment]
conflict appeared during merge stage so have to solve it before push.
line 447 in GFDL dev/master: 
      fluxes%lrunoff(i,j) = kg_m2_s_conversion * IOB%lrunoff(i-i0,j-j0) * G%mask2dT(i,j)

line 447 in dev/emc
      fluxes%lrunoff(i,j) = IOB%lrunoff(i-i0,j-j0) * G%mask2dT(i,j)

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang  I think I figured out where the confusion is coming from.  When you resolved the conflicts from the merge, added the file and then went to commit, you put the commit message "solve conflice in mom_surface_forcing_nuopc.F90 " whereas usually with a merge commit we're used to seeing something like "Merge remote-tracking branch..."

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA is right. And I personally at least think it leads to a lot of confusion in the commit history. I had struggled earlier trying to unwind the commit history at the Jan 2020 commit probably for the same reason. I think it makes much more sense to have the commit message be 'merge  remote ...' Otherwise the commit message implies to me that you merged in gfdl and then made a second commit where you changed something in dev/emc.

**Comment by jiandewang** [comment]
fully agree, should contain more info in commit history.

**Comment by DeniseWorthen** [comment]
@jiandewang could we fix this on this PR and going forward? This would mean re-doing what you've done; the other option might be to amend your commit message that you've already pushed. Googling says that is possible but seems a bit complicated (?)

The commit message would be 'merge remote ' etc and then additionally on the next line you could add that you fixed conflict in the subroutine.

**Comment by jiandewang** [comment]
one simple solution is adding one line in README.md, commit with note of what we need, let me know if this sounds good or not.

**Comment by JessicaMeixner-NOAA** [comment]
That would mean we would constantly have to fix conflicts and maintain a file that is purposefully different from dev/master.  I think that adds more work for the future. When we push back to GFDL, NCAR or others they would always have to go find that we added things to the README that they do not want, etc.   I think the commit message history is the right place for this information.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Yes, I agree. We need a clean commit history that clearly indicates that we've merged to master. I personally don't think it is necessary to have noted what conflicts were fixed, but if want to include that additional information then a second line in the commit message is the place to do it.

**Comment by jiandewang** [comment]
what about now:
https://github.com/jiandewang/MOM6/commit/e8c05f1c95efe5ea2fe0faa43f69f294c151be6e

**Comment by DeniseWorthen** [comment]
Can you do a git --amend and change it to read:

merge GFDL dev/master 20200401 commit (hash # 010492e2)
solve conflict in mom_surface_forcing_nuopc.F90

**Comment by jiandewang** [comment]
done.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]
Thanks for changing the commit message Jiande. 

I've confirmed that the debug fix is still in the MOM_wave_interface routine. Since this doesn't change answers, it is fine to commit.

**Pull request merged**
