### PR TITLE
Feature/update to gfdl 20210308

### LINKED ISSUE #60: update MOM6 to GFDL 20210308 commit
GFDL updated its main branch on 20210308 which contains their 2nd step of changes related to the using of FMS2. EMC will need to make corresponding changes.

### PR DESCRIPTION
**Pull request by jiandewang**
**Description of changes**

- update EMC MOM6 to GFDL 20210308 commit (see detail at https://github.com/NOAA-GFDL/MOM6/pull/1342)

**Issues Fixed (include github issue #):**

- MOM6 closes #60 

- ufs-weather-model Issue 457 (https://github.com/ufs-community/ufs-weather-model/issues/457)

**Are changes expected to change answers?**

- No

**Testing performed**:

- machine: orion, hera and dell-p3

**Hashes used for testing**

- NEMS: b80b5b18

- CMEPS: 0658dde

- FV3: ddb56fe8

- CICE: f773ef38

- WW3: a89e2a6

- stochastic_physics: c39bb8a

- MOM6: 3703ca7 (https://github.com/jiandewang/MOM6/tree/feature/update-to-GFDL-20210308)

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
In the main comment to the PR, If you change:
"MOM6 Issue #60" to "Closes #60", then the merge of this PR will automatically close that issue.

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA Thanks for the useful information. BTW, do you think the change I made in this PR is fine ? I made test run without problem.

**Comment by BrianCurtis-NOAA** [comment]
I haven't looked through anything, but I don't know much about the MOM6 source code. I only read through the makefile while working on the cmake port.

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA there is no any code content change of MOM6 in this PR, the changes are on directory structure

**Comment by jiandewang** [comment]
the changes in MOM6 directories are:
(1) rename config_src/nuopc_driver to config_src/drivers/nuopc_cap
(2) rename config_src/solo_driver to config_src/driver/solo_driver
(3) extract all infra.F90 files from src/framework to src/config_src/infra/FMS1
(4) rename config_src/dynamic to config_src/memory/dynamic_nonsymmetric

**Comment by BrianCurtis-NOAA** [comment]
The directory structure changes will need to be noted for the MOM6-interface in ufs. At first glance there will be file locations to update in mom6_files. But thats just to note for when you work on the PR over in ufs.

**Comment by jiandewang** [comment]
@BrianCurtis-NOAA yes I put them on ufs PR, see https://github.com/ufs-community/ufs-weather-model/pull/458

**Review by DeniseWorthen — APPROVED** [review]

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
