### PR TITLE
Add cmeps compatibility

### PR DESCRIPTION
**Pull request by DeniseWorthen**
This PR resolves issue #9 by 

1. enable reading of the overwrite attribute from nems.configure (false by default for NEMS)

2. adding mom_export in DataInitialize 

3. adding the scalar fields if the scalar_field_name is longer than the default of 0.

All regression on Hera Pass. See logs [https://github.com/DeniseWorthen/ufs-s2s-model/tree/feature/addcmeps](https://github.com/DeniseWorthen/ufs-s2s-model/tree/feature/addcmeps)

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Nothing for the restarts?

**Comment by DeniseWorthen** [comment]
I see the restarts passed in the hera logs for the 2d tests.

**Comment by JessicaMeixner-NOAA** [comment]
I meant as one of the differences we had in CMEPS before with the #ifdefs 

It was: 
1. no if cesm for the data_initalize 
2. the overwrite #ifdef -> attribute 
3. scalar fields 
4. There was an if def around the restarts

But maybe that was just to stop getting double restarts which we can live with for now? ... Which reminds me I need to add intermediate restarts back for NEMS....

**Comment by DeniseWorthen** [comment]
That was added in an attempt to fix the double restarts. We get restarts as normal in the NEMS case. I believe we will get double restarts when run with CMEPS.

**Pull request merged**
