### PR TITLE
unlock restart registry to add oda_incupd_ncount

### PR DESCRIPTION
**Pull request by pjpegion**

### CODE REVIEW

**Comment by pjpegion** [comment]
@jiandewang Can you check to if my addition of the unlocking of the restart file violates some coding standard?

**Comment by jiandewang** [comment]
@pjpegion can you add a space before restart_registry_lock ?
https://github.com/NOAA-EMC/MOM6/pull/83/files?diff=unified&w=0#diff-10cfe73262268a82e836dae8f2dbd0fb59656fac67455ada3fe69c3c6dd14c88R29

**Comment by jiandewang** [comment]
this PR will be replaced by an identical PR from FSU to MOM6 main (https://github.com/mom-ocean/MOM6/pull/1559)

**Comment by jiandewang** [comment]
this is done through https://github.com/ufs-community/ufs-weather-model/pull/1136

**Pull request closed without merging**
