### PR TITLE
Feature/update to gfdl 20210402

### LINKED ISSUE #64: update MOM6 code from GFDL (20210402)
It was noticed that the codes between EMC dev/emc and GFDL main branch contain some minor difference due to a mistakenly clicking of button by GFDL on 20210308's updating. A hot fixing will bring two sides' code on the same page again. See detail at https://github.com/NOAA-GFDL/MOM6/pull/1358

GFDL updated main branch on 20210402 (see detail at https://github.com/NOAA-GFDL/MOM6/pull/1358#event-4545482872). This updating will make EMC and GFDL main repository on the same page.

### PR DESCRIPTION
**Pull request by jiandewang**
**Description of changes**

update EMC MOM6 to GFDL 20210402 commit (see detail at https://github.com/NOAA-GFDL/MOM6/pull/1358#issuecomment-811919139)

**Issues Fixed (include github issue #):**

MOM6 closes #64 

ufs-weather-model Issue 489 (https://github.com/ufs-community/ufs-weather-model/issues/489)

Are changes expected to change answers?

No
Testing performed:

machine: orion, hera and dell-p3
Hashes used for testing

NEMS: b80b5b1

CMEPS: 0658dde

FV3: ebccc53

CICE: f773ef38

WW3: fc509248a

stochastic_physics: d0e62eb2

MOM6: c549ae9d9 (https://github.com/jiandewang/MOM6/tree/feature/update-to-GFDL-20210402)

### CODE REVIEW

**Comment by jiandewang** [comment]
passed RT in all platforms, ready for review

**Review by DeniseWorthen — APPROVED** [review]
Looks fine. Thanks for taking the opportunity to get the topo edits change in.

**Comment by JessicaMeixner-NOAA** [comment]
This is being merged into ufs-weather-model with this PR: https://github.com/ufs-community/ufs-weather-model/pull/488 correct?

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by jiandewang** [comment]
> This is being merged into ufs-weather-model with this PR: [ufs-community/ufs-weather-model#488](https://github.com/ufs-community/ufs-weather-model/pull/488) correct?

correct

**Pull request merged**
