### PR TITLE
update MOM6 to its main branch commit 20211220

### PR DESCRIPTION
**Pull request by jiandewang**
need to update MOM6 to its main branch commit 20211220 (see detail at https://github.com/mom-ocean/MOM6/pull/1538).
This updating contains stochastic physics code further modification 
Related issue #80

### CODE REVIEW

**Comment by jiandewang** [comment]
note the related ufs PR is combined at 
https://github.com/ufs-community/ufs-weather-model/pull/976

**Comment by jiandewang** [comment]
all RT passed (see detail at https://github.com/ufs-community/ufs-weather-model/pull/976)
@JessicaMeixner-NOAA can you do code review for this ? I think Denise is on A/L

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang apologies, had travel delays.  I'm doing the review now.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Code is the same as mom-ocean/MOM6 main

**Comment by jiandewang** [comment]
close

**Pull request merged**
