### PR TITLE
update to main 20221112 commit

### PR DESCRIPTION
**Pull request by jiandewang**
MOM6 main repo was updated on 20221112, this is originally from dev-gfdl-candidate-20221027, see detail at https://github.com/mom-ocean/MOM6/pull/1586. Note the default value of KVML is changed from 1E-4 to 0. By following MOM6-examples, we will set this explicitly in MOM_input. Also several variables were removed from restart files while 3 new variables were added but the original style of restart files can be preserved by setting STORE_CORIOLIS_ACCEL = False

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Code matches mom6 main and ufs regtests passed

**Comment by BrianCurtis-NOAA** [comment]
> Code matches mom6 main and ufs regtests passed

@JessicaMeixner-NOAA Anything to be concerned about the test failures for MacOS and Regression?

**Comment by JessicaMeixner-NOAA** [comment]
> > Code matches mom6 main and ufs regtests passed
> 
> @JessicaMeixner-NOAA Anything to be concerned about the test failures for MacOS and Regression?

I did not see that the MacOS regression tests failed -- I skimmed the UFS tests and misssed that (i looked at hera in detail) and thought others said everything passed execpt acorn which would be skipped.  

Is MacOS a supported platform for UFS?

**Comment by BrianCurtis-NOAA** [comment]
> > > Code matches mom6 main and ufs regtests passed
> > 
> > 
> > @JessicaMeixner-NOAA Anything to be concerned about the test failures for MacOS and Regression?
> 
> I did not see that the MacOS regression tests failed -- I skimmed the UFS tests and misssed that (i looked at hera in detail) and thought others said everything passed execpt acorn which would be skipped.
> 
> Is MacOS a supported platform for UFS?

OK Sounds good to me. UFS supports only Tier 1 systems. Thanks.

**Comment by JessicaMeixner-NOAA** [comment]
@BrianCurtis-NOAA i now see what you mean about the macOS regression test here.  Im not sure why these are failing as these pass here: https://github.com/mom-ocean/MOM6 and the code is the same... 

We should figure that out eventually but I don't think this is a concern for now. @jiandewang might be able to say more.

**Comment by jiandewang** [comment]
> @BrianCurtis-NOAA i now see what you mean about the macOS regression test here. Im not sure why these are failing as these pass here: https://github.com/mom-ocean/MOM6 and the code is the same...
> 
> We should figure that out eventually but I don't think this is a concern for now. @jiandewang might be able to say more.

agree with Jessica , will wait for Denise's review before merging

**Comment by DeniseWorthen** [comment]
Sorry, would have sworn I reviewed already.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jiandewang** [comment]
got greenlight from @JessicaMeixner-NOAA and @DeniseWorthen, I am going to do the merging

**Pull request merged**
