### PR TITLE
add statediagnose feature

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Fix for issue #30 

- Adds an optional state_diagnose feature to mom6 nuopc cap to write the min,max and sum of the import and export fields. This feature is controlled by a debug flag which can be set at run time using a new setting in the nems.configure. If the flag does not exist in the nems.configure, no error will result and the debug flag will be set to the default value of 0 (no diagnose output will be generated. 

- A small change is introduced to read the restart setting from input.nml. This replicates current behavior but is now explicit. 

- No change to current baselines. Logs are posted at S2S-PR [#155](https://github.com/ufs-community/ufs-s2s-model/pull/155)

co-author: @mvertens (state_diagnose code pulled from CICE6 nuopc/cmeps cap)

### CODE REVIEW

**Comment by jiandewang** [comment]
look good, do you have a run where I can take a look for the file which contains "min,max and sum of the import and export fields" information ?

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Admittedly I have not tested or run with this but the changes themselves look good.

**Comment by jiandewang** [comment]
this is a nice feature which will provide useful information when debugging. Since your runs passed all RT, I am going to approve it.

**Review by jiandewang — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
@jiandewang : Look at PET240 in this run on orion:

/work/noaa/stmp/dworthen/stmp/dworthen/S2S_RT/rt_108228/cpld_fv3_ccpp_mom6_cice_cmeps_2d_atm_flux

Import state variables are given by the ":IS:" lines and export state by the ":ES:" lines.

**Comment by jiandewang** [comment]
look nice, what does "12960" mean here ?
ES: sea_surface_temperature  0.000000      281.3567      204936.7       12960

**Comment by DeniseWorthen** [comment]
That is the number of values. I'm not sure why it is useful.

**Pull request merged**
