### PR TITLE
add temperature limiter for SPPT

### PR DESCRIPTION
**Pull request by pjpegion**
I have added a check for the temperature after to SPPT perturbation, and if it is too cold, set it to -1.8.  
This addresses issue https://github.com/NOAA-EMC/MOM6/issues/96

### CODE REVIEW

**Comment by jiandewang** [comment]
@pjpegion since your change is so tiny, I will include it in my pending PR https://github.com/NOAA-EMC/MOM6/pull/95

**Comment by jiandewang** [comment]
@pjpegion things are a bit complicated as yours is based on dev/emc while mine is for merging from main branch. So I manually added your one line change in mine (https://github.com/NOAA-EMC/MOM6/pull/95).
Can you take a quick look to make sure it is correct ?
https://github.com/NOAA-EMC/MOM6/pull/95/files#diff-fd384abbba9b69756698159085ed7e3a10123889a5f3feb3ea130cf985ff9679R453

also your change will change datm_cdeps_stochy_gefs job answer, right ?

**Comment by pjpegion** [comment]
@jiandewang the code change looks right, and yes, this changes the result to datm_cdeps_stochy_gefs

**Comment by jiandewang** [comment]
@pjpegion thanks for the double checking, let's wait for my UFS turn to have this done.

**Pull request closed without merging**
