### PR TITLE
update to main 20240228 commit

### PR DESCRIPTION
**Pull request by jiandewang**
This is a big PR which originally was GFDL 20231113 candidate PR (https://github.com/mom-ocean/MOM6/pull/1616).
The original PR failed to retain UFS BL on wcoss2 but are fine on all other platforms. With Marshall and Bob's further modification, it can retain UFS BL on wcoss2 for 1x1, half and quarter degree settings now. Discussion on the root cause of the original failing of retain BL can be found in the original PR (https://github.com/mom-ocean/MOM6/pull/1616) and the last commit from Marshall in ths PR.
 new BL are needed for:

- cpld_control_c48: two new variables are being added in this setting (p_surf_EOS=True), this is why you will see all files are OK in cmp except ocean restart files on all platforms (except wcoss2). For wcoss2 it changed answers.
- hafs_regional_storm_following_1nest_atm_ocn_wav_mom6: a bug fixing is included which changed answer in this PR

note the original DEFAULT_2018_ANSWERS=T has changed to DEFAULT_ANSWER_DATE=20181231 in MOM_input

### CODE REVIEW

**Comment by zach1221** [comment]
Hello, @DeniseWorthen and @JessicaMeixner-NOAA , this PR is now ready for review.

**Review by DeniseWorthen — APPROVED** [review]

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by jiandewang** [comment]
got greenlight from two reviewers now.

**Comment by zach1221** [comment]
@jiandewang regression testing is complete on 2166, and we can begin the final review/merge process. Can you please merge this MOM6 PR for us?

**Comment by jiandewang** [comment]
just merged

**Pull request merged**
