### PR TITLE
update MOM6 to its main 20231218 commit (disable FPEs)

### PR DESCRIPTION
**Pull request by jiandewang**
MOM6 main repository was updated on 20231218 to fix FPEs bug in its CI test. (see detail at https://github.com/mom-ocean/MOM6/pull/1617). This is a very simple PR with no any resuls change. Related dev/emc MOM6 issue is #123. We need to have this being merged to dev/emc before we can create PR to push @DeniseWorthen work back to main repository.

### CODE REVIEW

**Comment by jiandewang** [comment]
@DeniseWorthen @JessicaMeixner-NOAA can you review this PR ?

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jkbk2004** [comment]
Tests are done at https://github.com/ufs-community/ufs-weather-model/pull/2080. @DeniseWorthen @JessicaMeixner-NOAA can you merge this pr?

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang can you do the merge?

**Comment by jiandewang** [comment]
just merged

**Pull request merged**
