### PR TITLE
Feature/update to gfdl 20201022

### PR DESCRIPTION
**Pull request by jiandewang**
**Description of changes**
update EMC MOM6 to GFDL 20201022 commit

Specific notes

**Issues Fixed** (include github issue #):
MOM6 Issue #39 
ufs-weather-model Issue 283 (https://github.com/ufs-community/ufs-weather-model/issues/283)

**Are changes expected to change answers?**
- yes
When using this new MOM6 code which contains some default value changes, the original results can be retained for 0.25x0.25 degree setting by explicitly adding several parameters in MOM_input_025, detail can be seen at https://github.com/jiandewang/ufs-weather-model/blob/feature/update-MOM6-retain-b4b-025/tests/parm/MOM_input_template_025#L12. However there are 4 variables being removed from restart file MOM.res-2.nc, so will fail in cmp but the common variables are b4b identical.

**Testing performed**:

- machine: orion, hera and dell-p3

**Hashes used for testing**

- NEMS: 251d70c3a

- CMEPS: efb8d353

- FV3: 4fdf7c6f

- CICE: ac617cde

- FV3: 4fdf7c6f1

- WW3: 9c22b135

- stochastic_physics: 6eac8455

- MOM6: aff9c2c6 (https://github.com/jiandewang/MOM6/tree/feature/update-to-GFDL-20201022)

### CODE REVIEW

**Comment by jiandewang** [comment]
[Log from orion.pdf](https://github.com/NOAA-EMC/MOM6/files/5563040/Log.from.orion.pdf)
[Log fro HERA.pdf](https://github.com/NOAA-EMC/MOM6/files/5563041/Log.fro.HERA.pdf)
add log file from orion and hera

**Comment by JessicaMeixner-NOAA** [comment]
Instead of posting the log files, can you just point to the UFS-weather-model PR?  I'm assuming there is a corresponding one?

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA Are we doing 2 PRs on ufs-weather too? Given the slow commit queue on ufs-weather, couldn't the update to ufs-weather be done only once (after the new default setings are used). The update here is for the code; jiande can show the code is b4b if we switch the input settings. The input setting updates  would go w/ the code update to ufs-weather.

**Comment by jiandewang** [comment]
[DELL log.pdf](https://github.com/NOAA-EMC/MOM6/files/5563734/DELL.log.pdf)
add dell log
no ufs-weather-model PR yet, will coming soon.
branch targeted  for PR: https://github.com/jiandewang/ufs-weather-model/tree/feature/update-MOM6-retain-b4b-025

**Comment by JessicaMeixner-NOAA** [comment]
It will only be 1 commit to MOM6 but I think there should be 2 commits to ufs-weather-model -- one with the parameters being explicitly set from to maintain current answers, one to update parameters. l I guess can look in the PR follow links and see that the parameters are explicitly changed are: 
MIN_SALINITY = 0.01
FIX_UNSPLIT_DT_VISC_BUG = False
Z_INIT_REMAP_OLD_ALG = True
FIX_USTAR_GUSTLESS_BUG = False
REMAP_UV_USING_OLD_ALG = True
USE_LAND_MASK_FOR_HVISC = False
USE_GM_WORK_BUG = True
KAPPA_SHEAR_ITER_BUG = True
KAPPA_SHEAR_ALL_LAYER_TKE_BUG = True
DEFAULT_2018_ANSWERS = True
USE_PSURF_IN_EOS = False

I guess if the parameters that are changed are explicitly enough documented one commit will have to work, but if a slow queue is a reason to always make massive commits... that's not really a good place to be in either.

**Comment by DeniseWorthen** [comment]
Thinking about this more, what I think is actually most important is that we can retain restart repro w/ the updated MOM6 and the new defaults for all resolutions. Shan and I have been using a specific cpld_restart branch to test this; I've made a new branch which points to the updated MOM6: [cpld_restart_updatemom](https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/cpld_restart_updatemom). 

@jiandewang can you use this branch to test for restart repro with the new defaults and the updated MOM6? You'll need to add that branch to your own ufs-weather fork and then change the MOM templates for the three resolutions. The original restart-repro issue and the branch description are in this ufs-weather [issue](https://github.com/ufs-community/ufs-weather-model/issues/227). 

To test, use:  ``./rt.sh -fek -l rt.cpldrestart.conf >output 2>&1 &`` and then compare the mediator restart files between control and the restart runs. The comparison has to be done manually since you're not comparing against baseline. It is set up now to do the non-frac case. If you get restart repro with non-frac, we need to then check for the frac-grid case. You can do this by changing to these settings in default_vars:

``CPLMODE='nems_frac``
``FRAC_GRID='.T.'``

Let me know if you have any questions. Thanks.

**Comment by jiandewang** [comment]
@DeniseWorthen I can make that test but I think the root cause is related to a halo bug which is not in this commit yet. Can you help me generate "rt.cpldrestart.conf" file based on my current file at /work/noaa/marine/Jiande.Wang/UFS-weather/JW-M6-up-025-only/JW-b4b-025-only/tests/rt.conf-JW, I think all you need is to delete some test case

**Comment by DeniseWorthen** [comment]
The original cpld_restart branch that Shan and I were using contained the vertex shear halo bug fix. We got restart repro w/ both frac and non-frac grid in this branch (using some changes to fv3). What I want to make sure is that we retain restart repro for frac_grid and non-frac grid when we update MOM6. 

You need to just checkout the branch I pointed you to (which contains the updated MOM6), change the templates to the new default ones you are proposing and run the rt.cpldrestart.conf with the command I gave you. Then do a cmp between the restart and the control directories at each resolution.

**Comment by jiandewang** [comment]
@DeniseWorthen got restart repro w/ both frac and non-frac grid in this new MOM code

**Review by DeniseWorthen — APPROVED** [review]
Getting b4b results in the 025 case and retaining restart repro for both frac grid T/F were both important to test. I think is good to go.

**Pull request merged**
